### DISCUSSION TITLE
Config file

### DISCUSSION THREAD

**Discussion by dmsims** [Sleeper85/esphome-yambms#12] [Ideas]
Currently each time there is a new release various values may have to be edited including Board type, Cell count, voltages, BLE MAC etc

Consider putting these variables into a config file?

**Comment by Sleeper85** [comment]
The main YAML is your config file, I try not to make too many changes to keep it compatible but I admit that often there are changes.
I will think about this question.

**Comment by Sleeper85** [comment]
I just did a first test and there are several possibilities to do this.

But really you just need to keep and reuse `your main YAML` and replace the `packages` folder.
Putting information elsewhere in another file won't change much if I change or add an option, you'll need to edit your config file in that case.

**Comment by Sleeper85** [comment]
Create a `yambms_config.yaml` file with your settings.

Example `yambms_config.yaml`
```YAML
substitutions:
  config_bms1_option1: 'option1'
  config_bms2_option1: 'option1'
  config_yambms1_yambms_id: 'yambms1'
  config_yambms1_canbus_id: 'canbus1'
  config_canbus1_option1: 'option1'
```
Import it and replace in the main YAML the values ​​with the substitution variables from your config file.

Example `yambms_main.yaml`
```YAML
packages:
  # Your config files
  yambms_config: !include yambms_config.yaml
  #
  device_base: !include packages/base/device_base.yaml
  device_board: !include packages/board/board_esp32-devkit-v1.yaml
  
  yambms1: !include
    file: packages/yambms/yambms.yaml
    vars:
      yambms_id: ${config_yambms1_yambms_id}
      yambms_name: ${config_yambms1_canbus_id}
```
I don't know what to think about it, it adds complexity in some cases unnecessary and this could also allow to maintain several `YamBMS` based on the same config file and change options in one place.

In both cases, both styles can exist, either enter the values ​​directly in the main file or use a config file.
