### DISCUSSION TITLE
[ETH01-EVO POE] compilation problem with `DM9051` Ethernet component

### DISCUSSION THREAD

**Discussion by Imanol82** [Sleeper85/esphome-yambms#2] [Q&A]
Hello!

I'm making a new version of the yambms to put inside the box I printed in 3D. 
I have already soldered all the wires and when I start to compile the yambms.yaml that I have running to install it on this new board I get this error. 
What am I doing wrong?

![Captura de pantalla 2024-11-02 124758](https://github.com/user-attachments/assets/4b7b15af-1e6f-439d-a87c-12caf28ffc9e)

Thank you very  much!!

**Comment by Sleeper85** [comment]
The problem comes from the import of the external component, some things have changed but I don't know what.

```YAML
external_components:
  - source: github://pr#6861
    components:
      - ethernet
```

https://github.com/esphome/esphome/pull/6861

**Comment by Imanol82** [comment]
I've remake all with the old esp32 eth01.
It works because it had de firmware installed. I can't update but it works.

I'll investigate what has changed. 

The result:

![IMG_20241103_124749](https://github.com/user-attachments/assets/6bdb2c77-8618-4010-a72c-cd662c3db7ac)

![IMG_20241103_125247](https://github.com/user-attachments/assets/0f4de680-80b5-4631-b862-77199c4152b3)

Thanks!!

**Comment by Imanol82** [comment]
Hello my friend. I don't know why my answer has disappeared...



Yesterday after last update... boooom! hahaha

Comunication between Deye, YamBMS and BMSs work fine, but I can't see nothing in HA! hahaha

![image](https://github.com/user-attachments/assets/bfeaa9fe-fe4b-4c99-b795-5229a686b05b)
(forget the middle area, I have been working on the installation and the battery has been disassembled)


![image](https://github.com/user-attachments/assets/a66bbe79-55e5-424c-bf26-ec9c15bf289d)


![image](https://github.com/user-attachments/assets/d9bb885c-1c70-48de-829c-bc41589e3852)

How angry it is when things break due to updating... hahaha

Thanks my friend and sorry for being so annoying.

**Comment by Sleeper85** [comment]
https://github.com/home-assistant/supervisor/issues/5405

What is your HA server version?

I read that there are issues with the latest version.

Can you completely remove your ESP32 and its entities from HA.

Do a clean build before compiling again?

PS: the new YamBMS `1.5.1` version will be released soon.

**Comment by Imanol82** [comment]
Yes, I've updated...

![Screenshot_2024-11-13-06-00-27-240_io homeassistant companion android](https://github.com/user-attachments/assets/a3483411-18dc-4264-9d48-b921e5d610f9)

To install it, I copy the folder to the esphome folder, modify the yaml you mentioned in a previous conversation (for the ethernet) and change the general yaml to 1.4.5. And that's what I compile and install again. This is not correct?

**Reply by Sleeper85** [reply]
> To install it, I copy the folder to the esphome folder, modify the yaml you mentioned in a previous conversation (for the ethernet) and change the general yaml to 1.4.5. And that's what I compile and install again. This is not correct?

Yes

**Reply by Sleeper85** [reply]
From my reading it seems that the version of HA you have installed is currently causing problems.

**Comment by Sleeper85** [comment]
From my reading it seems that the version of HA you have installed is currently causing problems.

**Comment by Imanol82** [comment]
Ok. I'll wait them.
Without HA YamBMS continue working so it's ok tonwait.

As always, thank you very much

**Comment by Imanol82** [comment]
Hello @Sleeper85 , I'm back!

I'll try again you project. Txubelaxu's one works fine but as all of us, I can't be without trying things hehe.

One suggestion, as your esp32 project used to be installed near the inverter, don't you think good idea to use 2 more GPIOs to use a PWM fans for example? For inverter or for the batteries... But i think this is something usefull.

I'm doing on a separate esp32 to.control 48v pwm fans but maybe is interestig to merge in your code...

Thanks!!

**Reply by Sleeper85** [reply]
What code are you currently using for PWM fans ?

**Reply by Imanol82** [reply]
This:

```
substitutions:
  settings_skipped_updates: "30"
  devicename: "deye_fan"

  #FAN Blue Cable TACH (normalmente amarillo)
  pulse_counter_1: GPIO00 
  pulse_counter_2: GPIO18
  pulse_counter_3: GPIO19

  #FAN Yellow Cable PWM (normalmente azul)
  output: GPIO04

esphome:
  name: $devicename

esp32:
  board: esp32-c3-devkitm-1
# currently needed, but not in the future
  variant: esp32c3
  framework:
    type: esp-idf
    version: latest

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: 

ota:
  - platform: esphome
    password: 

external_components:
  - source: github://pr#6861
    components:
      - ethernet
    refresh: 1d

ethernet:
  type: DM9051
  clk_pin: GPIO07
  mosi_pin: GPIO10
  miso_pin: GPIO03
  cs_pin: GPIO09
  interrupt_pin: GPIO08
  reset_pin: GPIO06
  clock_speed: 20MHz
  manual_ip:
    static_ip: 192.168.178.111
    gateway: 192.168.178.1
    subnet: 255.255.255.0
    dns1: 192.168.178.1

    
################################################ FAN CONTROL ############################################


sensor:

  - platform: pulse_counter
    pin: 
      number: $pulse_counter_1
      mode:
        input: true
        pullup: true
    name: "Deye Fan 1 RPM"
    id: deye_fan_1_rpm
    update_interval: 1s
    unit_of_measurement: "RPM"
    filters:
      - multiply: 0.5

  - platform: pulse_counter
    pin: 
      number: $pulse_counter_2
      mode:
        input: true
        pullup: true
    name: "Deye Fan 2 RPM"
    id: deye_fan_2_rpm
    update_interval: 1s
    unit_of_measurement: "RPM"
    filters:
      - multiply: 0.5

  - platform: pulse_counter
    pin: 
      number: $pulse_counter_3
      mode:
        input: true
        pullup: true
    name: "Deye Fan 3 RPM"
    id: deye_fan_3_rpm
    update_interval: 1s
    unit_of_measurement: "RPM"
    filters:
      - multiply: 0.5

output:

  - platform: ledc
    pin: $output
    id: fan_pwm_raw
    frequency: 25000Hz

  - platform: template
    id: fan_pwm
    type: float
    write_action:
      lambda: |-
        if (state == 0) {
          id(fan_pwm_raw).set_level(0);
        } else {
          // Mapea de 0-1 al rango 0.13-1.0
          float real_state = 0.13 + (state * (1.0 - 0.13));
          id(fan_pwm_raw).set_level(real_state);
        }

fan:

  - platform: speed
    name: "Deye Fan"
    id: deye_fan
    output: fan_pwm
    restore_mode: RESTORE_DEFAULT_ON
    
    
```
