### ISSUE TITLE
[JK-PB RS485] - Low battery alarm

### ISSUE THREAD

**Issue by txubelaxu** [Sleeper85/esphome-yambms#10]
The ESP32-S3 is working now very stable. No reboots at all.
But, sometimes the Victron System reports "Low Battery" alarms.

![image](https://github.com/user-attachments/assets/fc704c44-c20e-4ec7-8c92-9424c6b27958)

But yambms battery voltage has been OK at those times:

![image](https://github.com/user-attachments/assets/4619157a-d717-4214-abf8-ac5ffe93e218)

![image](https://github.com/user-attachments/assets/25e66b66-18ee-4fe5-b594-51d4f3808b62)

I have disconnected BMS CANBUS from Cerbo GX. I suspect Cerbo GX detects "low battery" from CANBUS information arrived.

**Comment by txubelaxu** [comment]
Since I desconected CANBUS no "low battery" alarm. ESP32 very stable. No reboots.

**Comment by Sleeper85** [comment]
What is sent to the CAN bus is the voltage of the sensor `Total Voltage (Ø)` as you have shown in the graphs.

Is it possible to have a history of the values ​​received on the Victron side?

**Comment by txubelaxu** [comment]
I have not found any log in Victron side.

Could you create a debug sensor with the real info that is sent to canbus? This way I could betatesting it.

I have the system offlinecan and it has not detected low battery at all, despite the system has had tested very heavyly (0<P<7.5kW)

Many thanks!!!

**Comment by Sleeper85** [comment]
What is sent is what is published to the `YamBMS` sensors, creating a new sensor will not show anything more.

```YAML
            - if: # 0x356 - Actual Voltage / Current / Temperature / Cycles (Deye 0x305 ACK)
                condition:
                  lambda: return id(${canbus_id}_can_frame) == 4;
                then:
                  - canbus.send:
                      canbus_id: ${canbus_node_id}
                      can_id: 0x356
                      data: !lambda |-
                        // Byte [00:01] : Actual Voltage           (0.01 V)
                        // Byte [02:03] : Actual Current           (0.1 A)
                        // Byte [04:05] : Actual Temperature       (0.1 °C)
                        // Byte [06:07] : Actual Cycles number     (1 cycle)     (Sofar)
                        
                        uint8_t can_mesg[8];
                        
                        can_mesg[0] = uint16_t(id(${yambms_id}_total_voltage).state * 100) & 0xff;
                        can_mesg[1] = uint16_t(id(${yambms_id}_total_voltage).state * 100) >> 8 & 0xff;
                        can_mesg[2] = int16_t(id(${yambms_id}_current).state * 10) & 0xff;
                        can_mesg[3] = int16_t(id(${yambms_id}_current).state * 10) >> 8 & 0xff;
                        can_mesg[4] = int16_t(((id(${yambms_id}_min_temperature).state + id(${yambms_id}_max_temperature).state) / 2) * 10) & 0xff;
                        can_mesg[5] = int16_t(((id(${yambms_id}_min_temperature).state + id(${yambms_id}_max_temperature).state) / 2) * 10) >> 8 & 0xff;
                        can_mesg[6] = uint16_t(id(${yambms_id}_charging_cycles).state) & 0xff;
                        can_mesg[7] = uint16_t(id(${yambms_id}_charging_cycles).state) >> 8 & 0xff;
                        
                        // LuxPower
                        // Byte [04:05] : Max cell temperature     (0.1 °C)
                        // Byte [06:07] : Min cell temperature     (0.1 °C)

                        if (id(${canbus_id}_protocol).active_index() == 5)
                        {
                          // Added 0.1 °C safeguard to max temperature so that max and min values are never equal
                          can_mesg[4] = int16_t(id(${yambms_id}_max_temperature).state * 10 + 1) & 0xff;
                          can_mesg[5] = int16_t(id(${yambms_id}_max_temperature).state * 10 + 1) >> 8 & 0xff;
                          can_mesg[6] = int16_t(id(${yambms_id}_min_temperature).state * 10) & 0xff;
                          can_mesg[7] = int16_t(id(${yambms_id}_min_temperature).state * 10) >> 8 & 0xff;
                        }

                        ESP_LOGI("canbus", "send can_id: 0x356 hex: %x %x %x %x %x %x %x %x", can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]);
                        return {can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]};
```

What you can do is add an ESP32 on your CAN bus and read the CAN frames if you want to check what is sent on the CAN bus.

This code allows you to read and log all messages transmitted on the CAN bus :

```YAML
canbus:
  - platform: esp32_can
    id: canbus_sniffer
    tx_pin: 18 # to CAN board CTX
    rx_pin: 19 # to CAN board CRX (with 4.7K resistor except for SN65HVD230)
    can_id: 1
    bit_rate: 500kbps
    on_frame:
    - can_id:      0  # listen to all messages
      can_id_mask: 0
      use_extended_id: false # false = can_id 11 bits (PYLON), true = can_id 29 bits
      then:
        - lambda: |-
            ESP_LOGI("canbus", "received can_id: %x hex: %x %x %x %x %x %x %x %x", can_id, x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7]);
```
