### ISSUE TITLE
Poor performance of ESP32 Devkit V1

### ISSUE THREAD

**Issue by VolodymyrPavlyuk** [Sleeper85/esphome-yambms#16]
I have a Victron SmartShunt and three JK-PB BMSs and this is the maximum configuration which can run on my Devkit V1:
```yaml
packages:
  device_base: !include packages/base/device_base.yaml
  device_board: !include packages/board/board_esp32-devkit-v1.yaml

  # Config : this YAML contains the settings shared between all ESP32s
  config_yambms: !include packages/config/config_yambms.yaml

  shunt1: !include
    file: packages/shunt/shunt_combine_Victron_SmartShunt_BLE.yaml #
    vars:
      shunt_id: '1' # must be a number
      shunt_name: 'Shunt'
      shunt_mac_address: 'c9adfc3f5dc2'
      shunt_encryption_key: '908b0661a62f36c026424b21080fa4ae'

  # The sniffer represents the ESP node connected to the JK-BMS PB RS485 bus
  # If address 0x00 is not detected on the RS485 bus, the sniffer will act directly as a master BMS (mode 2, max 15 BMS)

  sniffer1: !include
    file: packages/bms/bms_combine_JK-PB_RS485_sniffer.yaml
    vars:
      sniffer_id: 'sniffer1'
      sniffer_protocol: 'JK02_32S'
      sniffer_uart_id: 'uart_esp_1'

  # Mode2 : configure the DIP switches of your BMS from 0x01 to 0x0F (don't use the 0x00 address, maximum 15 BMS)
  bms1: !include
    file: packages/bms/bms_combine_JK-PB_RS485_bms_minimal.yaml
    vars:
      # Sniffer ID
      sniffer_id: 'sniffer1'
      # BMS vars
      bms_id: '1' # must be a number
      bms_name: 'JK-BMS 1'
      bms_rs485_address: '0x01' # BMS 1 DIP switch
  
  # bms2: !include
  #   file: packages/bms/bms_combine_JK-PB_RS485_bms_minimal.yaml
  #   vars:
  #     # Sniffer ID
  #     sniffer_id: 'sniffer1'
  #     # BMS vars
  #     bms_id: '2' # must be a number
  #     bms_name: 'JK-BMS 2'
  #     bms_rs485_address: '0x02' # BMS 2 DIP switch

  # bms3: !include
  #   file: packages/bms/bms_combine_JK-PB_RS485_bms_minimal.yaml
  #   vars:
  #     # Sniffer ID
  #     sniffer_id: 'sniffer1'
  #     # BMS vars
  #     bms_id: '3' # must be a number
  #     bms_name: 'JK-BMS 3'
  #     bms_rs485_address: '0x03' # BMS 3 DIP switch
```
Even with this config esp resets every minute or so and the reason is `Software Reset CPU`:
<img width="2291" alt="image" src="https://github.com/user-attachments/assets/99bd6e60-4af1-4414-9583-3c29678d4371" />
<img width="2303" alt="image" src="https://github.com/user-attachments/assets/1d3bf103-07a7-4b24-beef-0311ff41ab0e" />

When I uncomment the second BMS the board resets 5 times and then just freezes.

Is this expected behaviour for such board or that's a sign that my board is defective?
