### ISSUE TITLE
Inverter Offset V. resets to 0V after each recompile/flash

### ISSUE THREAD

**Issue by AlexanderSch90** [Sleeper85/esphome-yambms#66]
Hi,

I noticed that the Inverter Offset V. slider value resets to 0V after each recompile or firmware flash. Other settings, such as CANBUS 1 BMS Name or CANBUS 1 Protocol, are retained correctly between flashes, so I was wondering:

Is this behavior intentional?

Or should the Inverter Offset V. value also persist across firmware uploads?

If not currently persistent, would it make sense to store it in a config file (e.g., YAML) or EEPROM so it survives reboots or updates?

This setting is quite important when compensating for voltage drop or calibration mismatches, so it would be very helpful if it could be preserved.

Thanks in advance!

**Comment by Sleeper85** [comment]
This is not normal, the value must be saved (`restore_value: true`).

Which version of esphome are you using ?

```YAML
  - platform: template
    name: "${name} ${yambms_name} Inverter Offset V."
    id: "${yambms_id}_inverter_offset_v"
    step: 0.1
    min_value: 0
    max_value: 1
    restore_value: true
    mode: "${yambms_input_number_mode}"
    initial_value: 0.0
    unit_of_measurement: V
    icon: mdi:sine-wave
    optimistic: true
    entity_category: config
```
